//aca se hace la solicutud a la API para obtener los eventos, mientras  q no hay api se usa un array de objetos
const Eventos = [
    {
        id: 1,
        titulo: "Evento 1",
        fecha: "2021-08-01",
        descripcion: "Descrpcion del evento 1",
        lugar: "Bienal",
        tematica: "River",

    },
    {
        id: 2,
        titulo: "Evento 2",
        fecha: "2021-08-01",
        descripcion: "Descrpcion del evento 2",
        lugar: "Bienal",
        tematica: "River",
    },
    {
        id: 3,
        titulo: "Evento 3",
        fecha: "2021-08-01",
        descripcion: "Descrpcion del evento 3",
        lugar: "Bienal",
        tematica: "River",
    },
    {
        id: 4,
        titulo: "Evento 4",
        fecha: "2021-08-01",
        descripcion: "Descrpcion del evento 4",
        lugar: "Bienal",
        tematica: "River",
    },
    {
        id: 5,
        titulo: "Evento 5",
        fecha: "2021-08-01",
        descripcion: "Descrpcion del evento 5",
        lugar: "Bienal",
        tematica: "River",
    },
    {
        id: 6,
        titulo: "Evento 6",
        fecha: "2021-08-01",
        descripcion: "Descrpcion del evento 6",
        lugar: "Bienal",
        tematica: "River",
    },
    {
        id: 7,
        titulo: "Evento 7",
        fecha: "2021-08-01",
        descripcion: "Descrpcion del evento 7",
        lugar: "Bienal",
        tematica: "River",
    },
    {
        id: 8,
        titulo: "Evento 8",
        fecha: "2021-08-01",
        descripcion: "Descrpcion del evento 8",
        lugar: "Bienal",
        tematica: "River",
    },
    {
        id: 9,
        titulo: "Evento 9",
        fecha: "2021-08-01",
        descripcion: "Descrpcion del evento 9",
        lugar: "Bienal",
        tematica: "River",
    },
    {
        id: 10,
        titulo: "Evento 10",
        fecha: "2021-08-01",
        descripcion: "Descrpcion del evento 10",
        lugar: "Bienal",
        tematica: "River",
    },
];
export default Eventos;